modLoader="javafml"
loaderVersion="[44,)"
license="MIT"

[[mods]]
modId="gildedsky"
version="0.0.01A-1.19.3"
displayName="Gilded Sky"
logoFile=""
credits=""
authors="Gilded Sky Team :: Lucian Rectanus"

description='''
=-=Gilded Sky=-=

A mod created to give a vanilla plus experience, adding new foods, animals, mobs, bosses, resources, and a new dimension.

- Version 0.001A
	Basic Blocks
'''

[[dependencies.gildedsky]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.gildedsky]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
